# Generated by Django 6.0.6 on 2026-07-02 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0002_add_slug_to_product"),
    ]

    operations = [
        migrations.AddField(
            model_name="address",
            name="zip",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
